name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Wlecome to world of bugs, where you learn from your own mistakes.'' first issue'
        pr-message: 'Welcome to community where you start contributing to organization to grow at a fast pace.'' first pr'
